targets:
  $default:
    builders:
      ts_schema_codegen|ts_schema:
        enabled: true
        options:
          source: schema/index.ts
          export: SCHEMA
          template: field_definitions
          field_class_import: package:ts_schema_codegen_composed_example/field_definition.dart
